version: "3.7"
services:
  redis:
    image: redis
    container_name: redis
    command: bash -c "redis-server --requirepass \"\" && redis-server --dir /home"
    networks:
      - my-network
    ports:
      - 6379:6379
    volumes:
      - /home/docker/redis/redis:/data
networks:
  my-network:
    external: true
