version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - local-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456aA@
      - MYSQL_PASSWORD=123456aA@
      - MYSQL_USER=root
      - MYSQL_DATABASE=Itd2902

networks:
    local-network:
      external: true